groups:
    - name: ContainerGroupRules
      rules:
      - alert: MonitoringContainerGroupMissingMembers
        expr: count(rate(container_last_seen{name=~".+",container_label_container_group=~"monitoring"}[5m])) by (container_group,host) < 6
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Container group warning"
          description: "{{ $labels.container_label_container_group }} is missing containers. Container count is {{ $value }}/13."
      