groups:
    - name: ContainerRules
      rules:
      - alert: HighCPUUsageOnContainer
        expr: sum(rate(container_cpu_usage_seconds_total{name=~".+"}[5m])) by (name,host) * 100 > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on container warning"
          description: "{{ $labels.name }} is using a LOT of CPU. CPU usage is {{ humanize $value}}%."

      - alert: PrometheusEatingMemory
        expr: sum(container_memory_rss{name=~"monitoring_prometheus_1"}) by (host, name) > 1200000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on prometheus warning"
          description: "{{ $labels.name }} is eating up a LOT of memory. Memory consumption of {{ $labels.name }} is at {{ humanize $value}}."