groups:
  - name: SiteRules
    rules:
    - alert: ServiceEndpointDown
      expr: probe_success{job='service'} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Endpoint service is non-operational"
        description: "Service {{ $labels.service_name }} with endpoint {{ $labels.service_url }} is not reachable. Please check whether the instance is running"
  
      