version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  master-nodeexporter:
    image: prom/node-exporter:latest
    expose:
      - 9100
    restart: always
    labels:
      container_group: monitoring

  master-cadvisor:
    image: google/cadvisor:latest
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    labels:
      container_group: monitoring
    ports:
      - ${CADVISOR_HOST_PORT:-8080}:8080

  prometheus:
    image: prom/prometheus:latest
    expose:
      - 9090
    volumes:
      - ${BASE_PROMETHEUS_PATH}:/etc/prometheus
      - prometheus_data:/prometheus
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    labels:
      container_group: monitoring
    ports:
      - ${PROMETHEUS_HOST_PORT:-9090}:9090

  blackboxprober:
    image: prom/blackbox-exporter:latest
    volumes:
      - ${BASE_BLACKBOXPROBER_PATH}:/etc/blackbox_exporter
    ports:
      - 9115:9115
    restart: always
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    labels:
      container_group: monitoring

  grafana:
    image: grafana/grafana:latest
    expose:
      - 3000
    restart: always
    labels:
      container_group: monitoring
    volumes: 
      - grafana_data:/var/lib/grafana
      - ${BASE_GRAFANA_PATH}:/etc/grafana/provisioning
    ports:
      - ${GRAFANA_HOST_PORT:-3000}:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}

  alertmanager:
    image: prom/alertmanager:latest
    expose:
      - 9093
    restart: always
    volumes:
      - ${BASE_ALERTMANAGER_PATH}:/etc/alertmanager/
      - ${BASE_ALERTMANAGER_PATH}/storage/alertmanager/:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    labels:
      container_group: monitoring
    ports:
      - ${ALERTMANAGER_HOST_PORT:-9093}:9093
