<<<<<<< HEAD
modules:
  http_2xx:
    prober: http
    timeout: 15s
    http:
      valid_status_codes: []
      method: GET
      preferred_ip_protocol: "ip4"
  http_post_2xx:
    prober: http
    timeout: 15s
    http:
      valid_status_codes: []
      method: POST
      preferred_ip_protocol: "ip4"
=======
# see https://github.com/prometheus/blackbox_exporter/blob/master/example.yml
modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
  http_post_2xx:
    prober: http
    timeout: 10s
    http:
      method: POST
  tcp_connect:
    prober: tcp
    timeout: 5s
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp
    timeout: 5s
>>>>>>> b05f86d... updated image tag versions, added rules in prometheus for alert management etc.
